/*
 * File: AddDatastream.js
 * Date: Fri Apr 08 2011 15:36:47 GMT-0300 (ADT)
 * 
 * This file was generated by Ext Designer version 1.1.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be generated the first time you export.
 *
 * You should implement event handling and custom methods in this
 * class.
 */

AddDatastream = Ext.extend(AddDatastreamUi, {
    initComponent: function() {
        AddDatastream.superclass.initComponent.call(this);
        var addWindow = this;
        var pid = decodeURIComponent(window.location.pathname.split('/')[3]);
        var form = this.get(0).getForm();
        var add = this.get(0).getFooterToolbar().get(0);
        var store = Ext.StoreMgr.lookup('Datastreams');

        add.addListener('click', function(button, event) {
            form.submit({
                url: '/adrcollection/ajax/addDatastream',
                params: {
                    pid: pid
                },
                success: function(form, action) {
                    var store = Ext.StoreMgr.lookup('Datastreams');
                    store.reload(store.lastOptions);
                    addWindow.close();
                },
                failure: function(form, action) {
                    switch (action.failureType) {
                        case Ext.form.Action.CLIENT_INVALID:
                            Ext.Msg.alert('Failure', 'Form fields may not be submitted with invalid values');
                            break;
                        case Ext.form.Action.CONNECT_FAILURE:
                            Ext.Msg.alert('Failure', 'Ajax communication failed');
                            break;
                        case Ext.form.Action.SERVER_INVALID:
                            Ext.Msg.alert('Failure', action.result.msg);
                    }
                }
            });
        });
    }
});
Ext.reg('addDatastream', AddDatastream);