/*
 * File: ADRCollectionViewer.js
 * Date: Sat Apr 02 2011 17:53:21 GMT-0300 (ADT)
 * 
 * This file was generated by Ext Designer version 1.1.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be generated the first time you export.
 *
 * You should implement event handling and custom methods in this
 * class.
 */

ADRCollectionViewer = Ext.extend(ADRCollectionViewerUi, {
    initComponent: function() {
        ADRCollectionViewer.superclass.initComponent.call(this);
        var overview;
        if(typeof(Overview) == "function" && typeof(Overview.prototype) == "object") {
            overview = this.add(new Overview());
        }
        if(typeof(Content) == "function" && typeof(Content.prototype) == "object") {
            this.activate(this.add(new Content()));
        }
        if(typeof(Manage) == "function" && typeof(Manage.prototype) == "object") {
            this.add(new Manage());
        }
        if(typeof(overview) != 'undefined' && window.location.hash == "#adr-collection-title") {
            this.activate(overview);
        }
    }
});
