/*
 * File: ADRCollectionViewer.ui.js
 * Date: Mon Nov 21 2011 14:45:01 GMT-0400 (AST)
 * 
 * This file was generated by Ext Designer version 1.1.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

ADRCollectionViewerUi = Ext.extend(Ext.TabPanel, {
    activeTab: 2,
    width: 960,
    border: false,
    id: 'adr-collection-tabpanel',
    initComponent: function() {
        ADRCollectionViewerUi.superclass.initComponent.call(this);
    }
});
