/*
 * File: CollectionProperties.js
 * Date: Mon May 16 2011 12:09:56 GMT-0300 (ADT)
 * 
 * This file was generated by Ext Designer version 1.1.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

CollectionProperties = Ext.extend(Ext.data.JsonStore, {
  constructor: function(cfg) {
    cfg = cfg || {};
    CollectionProperties.superclass.constructor.call(this, Ext.apply({
      storeId: 'ObjectProperties',
      url: '/adrcollection/ajax/getObjectProperties',
      autoLoad: true,
      baseParams: {
        pid: decodeURIComponent(window.location.pathname.split('/')[3])
      },
      fields: [{
        name: 'pid'        
      }, {
        name: 'label'
      }, {
        name: 'created'
      }, {
        name: 'modified'
      }, {
        name: 'owner'
      }, {
        name: 'state'
      }, {
        name: 'user'
      }],
      listeners: {
        load: function(store, records, options) {
          ADRCollection.pid = records[0].get('pid');
        }
      }
    }, cfg));
  }
});
new CollectionProperties();