/*
 * File: Content.js
 * Date: Thu Apr 07 2011 14:33:55 GMT-0300 (ADT)
 * 
 * This file was generated by Ext Designer version 1.1.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be generated the first time you export.
 *
 * You should implement event handling and custom methods in this
 * class.
 */

Content = Ext.extend(ContentUi, {
    initComponent: function() {
        Content.superclass.initComponent.call(this);
        var toolbar = this.getTopToolbar();
        var content_panel = this.get('adr-content-panel');
        var filter = toolbar.get('adr-content-filter');
        var search_type = toolbar.get('adr-content-search-type');
        var search_text = toolbar.get('adr-content-search-text');
        var add = toolbar.get('adr-content-add');
        content_panel.addListener('afterrender', function() {
            this.getFooterToolbar().doRefresh();
        });

        filter.addListener('change', function() {
            var filter = {
                "All Content": 'all',
                "Only Collections": 'collections',
                "Only Objects": 'objects'
            };
            var pager = content_panel.getFooterToolbar();
            var lastOptions = pager.store.lastOptions;
            lastOptions.params.filter = filter[this.activeItem.text];
            pager.store.reload(lastOptions);
        });

        search_type.addListener('change', function() {
            var search_type = {
                "Starts With": 'starts',
                "Contains": 'contains'
            };
            var pager = content_panel.getFooterToolbar();
            var lastOptions = pager.store.lastOptions;
            lastOptions.params.search_type = search_type[this.activeItem.text];
            pager.store.reload(lastOptions);
        });

        search_text.onTriggerClick = function(event) {
            var pager = content_panel.getFooterToolbar();
            var lastOptions = pager.store.lastOptions;
            lastOptions.params.search_text = search_text.getValue();
            pager.store.reload(lastOptions);
        };

        add.addListener('click', function() {
            var location = window.location;
            var page = location.protocol + '//' + location.host + '/formbuilder/ingest/';
            if(typeof(ADRCollection.pid) != 'undefined' && ADRCollection.pid != 'undefined') {
                page = page + ADRCollection.pid;
            }
            window.location = page;
        });
    }
});
Ext.reg('Content', Content);