/*
 * File: Content.ui.js
 * Date: Mon Apr 11 2011 07:35:03 GMT-0300 (ADT)
 * 
 * This file was generated by Ext Designer version 1.1.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

ContentUi = Ext.extend(Ext.Panel, {
    title: 'Content',
    initComponent: function() {
        ContentUi.superclass.initComponent.call(this);
    }
});
