/*
 * File: Content.js
 * Date: Thu Apr 07 2011 14:33:55 GMT-0300 (ADT)
 * 
 * This file was generated by Ext Designer version 1.1.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be generated the first time you export.
 *
 * You should implement event handling and custom methods in this
 * class.
 */

Content = Ext.extend(ContentUi, {
    initComponent: function() {
        Content.superclass.initComponent.call(this);
    }
});
Ext.reg('Content', Content);