/*
 * File: EditObjectWindow.js
 * Date: Tue Apr 19 2011 19:51:58 GMT-0300 (ADT)
 * 
 * This file was generated by Ext Designer version 1.1.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be generated the first time you export.
 *
 * You should implement event handling and custom methods in this
 * class.
 */

EditObjectWindow = Ext.extend(EditObjectWindowUi, {
    initComponent: function() {
        EditObjectWindow.superclass.initComponent.call(this);
        var editObjectWindow = this;
        var pid = ADRCollection.pid;
        var formPanel = this.get(0);
        var form = formPanel.getForm();
        var store = Ext.StoreMgr.lookup('ObjectProperties');
        var record = store.getAt(0);
        form.loadRecord(record);
        var save = formPanel.buttons[0];
        save.addListener('click', function(button, event) {
            form.submit({
                url: '/adrcollection/ajax/setObjectProperties',
                params: {
                    pid: pid
                },
                success: function(form, action) {
                    store.loadData(action.result.data);
                    editObjectWindow.close();
                },
                failure: function(form, action) {
                    switch (action.failureType) {
                        case Ext.form.Action.CLIENT_INVALID:
                            Ext.Msg.alert('Failure', 'Form fields may not be submitted with invalid values');
                            break;
                        case Ext.form.Action.CONNECT_FAILURE:
                            Ext.Msg.alert('Failure', 'Ajax communication failed');
                            break;
                        case Ext.form.Action.SERVER_INVALID:
                            Ext.Msg.alert('Failure', action.result.msg);
                    }
                }
            });
        });
    }
});
Ext.reg('editObjectWindow', EditObjectWindow);