/*
 * File: FileUploadField.ui.js
 * Date: Mon May 16 2011 12:09:56 GMT-0300 (ADT)
 * 
 * This file was generated by Ext Designer version 1.1.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

FileUploadFieldUi = Ext.extend(Ext.form.TextField, {
    allowBlank: false,
    initComponent: function() {
        FileUploadFieldUi.superclass.initComponent.call(this);
    }
});
