/*
 * File: Manage.js
 * Date: Thu Apr 07 2011 13:09:49 GMT-0300 (ADT)
 * 
 * This file was generated by Ext Designer version 1.1.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be generated the first time you export.
 *
 * You should implement event handling and custom methods in this
 * class.
 */

Manage = Ext.extend(ManageUi, {
    initComponent: function() {
        Manage.superclass.initComponent.call(this);
    }
});
Ext.reg('manage', Manage);