/*
 * File: xds_index.js
 * Date: Sat Apr 02 2011 17:53:21 GMT-0300 (ADT)
 * 
 * This file was generated by Ext Designer version 1.1.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

Ext.onReady(function() {
    Ext.QuickTips.init();
    var cmp1 = new ADRCollectionViewer({
        renderTo: Ext.getBody()
    });
    cmp1.show();
});
