/*
 * File: xds_index.js
 * Date: Fri Apr 08 2011 13:32:20 GMT-0300 (ADT)
 * 
 * This file was generated by Ext Designer version 1.1.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

Ext.onReady(function() {
    Ext.QuickTips.init();
    var cmp1 = new ADRCollectionViewer({
        renderTo: Ext.getBody()
    });
    cmp1.show();
    var cmp2 = new Overview({
        renderTo: Ext.getBody()
    });
    cmp2.show();
    var cmp3 = new Manage({
        renderTo: Ext.getBody()
    });
    cmp3.show();
    var cmp4 = new Content({
        renderTo: Ext.getBody()
    });
    cmp4.show();
});
